---
networks:
  my-network:

services:
  etl:
    build:
      context: ./
      dockerfile: ./Docker_ETL_Module/Dockerfile
    command: "sleep infinity"
    env_file:
      - "./Docker_ETL_Module/postgres.env"
    networks:
      - my-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    env_file:
      - "./Docker_ETL_Module/postgres.env"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/scripts/init_weather.sql:/docker-entrypoint-initdb.d/init_weather.sql
    ports:
      - "31477:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network