CREATE SCHEMA IF NOT EXISTS weather;

CREATE TABLE IF NOT EXISTS weather.weather_aggregated_data(
    id integer PRIMARY KEY,
    avg_temperature_2m_24h double precision NOT NULL DEFAULT 0.0,
    avg_relative_humidity_2m_24h double precision NOT NULL DEFAULT 0.0,
    avg_dew_point_2m_24h double precision NOT NULL DEFAULT 0.0,
    avg_apparent_temperature_24h double precision NOT NULL DEFAULT 0.0,
    avg_temperature_80m_24h double precision NOT NULL DEFAULT 0.0,
    avg_temperature_120m_24h double precision NOT NULL DEFAULT 0.0,
    avg_wind_speed_10m_24h double precision NOT NULL DEFAULT 0.0,
    avg_wind_speed_80m_24h double precision NOT NULL DEFAULT 0.0,
    avg_visibility_24h double precision NOT NULL DEFAULT 0.0,
    total_rain_24h double precision NOT NULL DEFAULT 0.0,
    total_showers_24h double precision NOT NULL DEFAULT 0.0,
    total_snowfall_24h double precision NOT NULL DEFAULT 0.0,
    avg_temperature_2m_daylight double precision NOT NULL DEFAULT 0.0,
    avg_relative_humidity_2m_daylight double precision NOT NULL DEFAULT 0.0,
    avg_dew_point_2m_daylight double precision NOT NULL DEFAULT 0.0,
    avg_apparent_temperature_daylight double precision NOT NULL DEFAULT 0.0,
    avg_temperature_80m_daylight double precision NOT NULL DEFAULT 0.0,
    avg_temperature_120m_daylight double precision NOT NULL DEFAULT 0.0,
    avg_wind_speed_10m_daylight double precision NOT NULL DEFAULT 0.0,
    avg_wind_speed_80m_daylight double precision NOT NULL DEFAULT 0.0,
    avg_visibility_daylight double precision NOT NULL DEFAULT 0.0,
    total_rain_daylight double precision NOT NULL DEFAULT 0.0,
    total_showers_daylight double precision NOT NULL DEFAULT 0.0,
    total_snowfall_daylight double precision NOT NULL DEFAULT 0.0,
    wind_speed_10m_m_per_s double precision[] NOT NULL DEFAULT '{0.0}',
    wind_speed_80m_m_per_s double precision[] NOT NULL DEFAULT '{0.0}',
    temperature_2m_celsius double precision[] NOT NULL DEFAULT '{0.0}',
    apparent_temperature_celsius double precision[] NOT NULL DEFAULT '{0.0}',
    temperature_80m_celsius double precision[] NOT NULL DEFAULT '{0.0}',
    temperature_120m_celsius double precision[] NOT NULL DEFAULT '{0.0}',
    soil_temperature_0cm_celsius double precision[] NOT NULL DEFAULT '{0.0}',
    soil_temperature_6cm_celsius double precision[] NOT NULL DEFAULT '{0.0}',
    rain_mm double precision[] NOT NULL DEFAULT '{0.0}',
    showers_mm double precision[] NOT NULL DEFAULT '{0.0}',
    snowfall_mm double precision[] NOT NULL DEFAULT '{0.0}',
    daylight_hours integer NOT NULL DEFAULT 0,
    sunset_iso timestamp NOT NULL UNIQUE DEFAULT 'now',
    sunrise_iso timestamp NOT NULL UNIQUE DEFAULT 'now'
)